apiVersion: v1
kind: Service
metadata:
  name: vlp-cloud-health-service
  namespace: vlp-cloud-health-service
  labels:
    app: vlp-cloud-health-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: vlp-cloud-health-service
